# Defaults
# SECRET_KEY="dev"
# HOST="http://localhost:5000"
# ROOT_USERNAME="root"
# ROOT_PASSWORD="password"
# AIRBYTE_API_URL="http://localhost:8001/api/public/v1"
# AIRBYTE_USERNAME="airbyte"
# AIRBYTE_PASSWORD="password"

# Needed config
KEAP_CLIENT_ID=""
KEAP_CLIENT_SECRET=""
INTERNAL_KEAP_ACCESS_TOKEN=""
INTERNAL_KEAP_REFRESH_TOKEN=""
AIRBYTE_WORKSPACE_ID=""
AIRBYTE_DESTINATION_KEAP_DEFINITION_ID=""
